#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/ddsm - database dependence supplementary modules
#
# IDENTIFICATION
#    src/backend/utils/ddsm/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/ddsm
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = mysm

include $(top_srcdir)/src/backend/common.mk