#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/commands/mys
#
# IDENTIFICATION
#    src/backend/commands/mysql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/commands/mysql
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	mys_tablecmds.o \
    mys_uservar.o 

include $(top_srcdir)/src/backend/common.mk

